### ISSUE TITLE
도커 및 도커 컴포즈 파일 구성

### ISSUE THREAD

**Issue by fkthfvk112** [emartFresh/emart-fresh#31]
## Description 💡
백-프론트를 통합한 도커 컴포즈 파일을 구성합니다.

## To-Do ✔️
- [x] 프론트 도커파일 생성 및 확인
- [x] 백 도커파일 생성 및 확인
- [x] 도커 컴포즈 생성 및 확인
